//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Especies_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        public int idSpecie { get; set; }
        public string CodeSpecie { get; set; }
        public string DescSpecie { get; set; }
    }
}
