//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesDades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int idCliente { get; set; }
        public string Nomclient { get; set; }
        public string Mail { get; set; }
        public int idCategoria { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
